     1	(*----------------------------------------------------------------------*)
     2	(*               ASCII character set definitions                        *)
     3	(*----------------------------------------------------------------------*)
     4	
     5	const
     6	  NUL  = 0;         (* NULL Character  *)
     7	  ETX  = 3;         (* ETX = ^C        *)
     8	  ENQ  = 5;         (* ENQ Character   *)
     9	  ACK  = 6;
    10	  BELL = 7;         (* BELL Character  *)
    11	  BS   = 8;         (* Backspace Char  *)
    12	  HT   = 9;         (* Horizontal Tab  *)
    13	  LF   = 10;        (* Line Feed       *)
    14	  VT   = 11;        (* Vertical Tab    *)
    15	  FF   = 12;        (* Form Feed       *)
    16	  CR   = 13;        (* Carriage Return *)
    17	  SO   = 14;        (* Start grahics   *)
    18	  SI   = 15;        (* End graphics    *)
    19	  XON  = 17;        (* XON  Character  *)
    20	  XOFF = 19;        (* XOFF Character  *)
    21	  CAN  = 24;
    22	  SUB  = 26;        (* EOF Character   *)
    23	  ESC  = 27;        (* Escape          *)
    24	  SP   = 32;        (* Space           *)
    25	  DEL  = 127;       (* DEL  Character  *)
    26	
